#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Przedmiot: Informatyka
# Kierunek studiów: Inżynieria Transportu 
# Semestr: zimowy
# Rok akademicki: 2020/2021
# Data (dzień.miesiąc.rok): 25.10.2020
# Imię: Wojciech 
# Nazwisko: Stempowski 
# Numer albumu ZUT: 43389

