#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Przedmiot: Informatyka
# Kierunek studiów: Inżynieria Transportu 
# Semestr: zimowy
# Rok akademicki: 2020/2021
# Data (dzień.miesiąc.rok): 25.10.2020
# Imię: Wojciech 
# Nazwisko: Stempowski 
# Numer albumu ZUT: 43389

while True : 
    liczba = int(input("wpisz liczbę:"))
    if liczba == 0:
        print("nie")
    else:
        if liczba == 1:
            print("raz")
        elif liczba == 2:
            print("dwa razy")
        elif liczba <= 9:
            print("kilka razy")
        elif liczba <= 19:
            print("kilkanascie razy")
        elif liczba <= 99:
            print("kilkadziesiat razy")
        else:
            print("wiele wile razy")
                       
                                          

